name: Build and Test

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin JDK
          java-version: '21' # Match your project's Java version

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project
      - name: Build with Maven
        run: mvn clean install --batch-mode

      # Step 5: Run tests
      - name: Run tests
        run: mvn test --batch-mode
